### ISSUE TITLE
com.intellij.diagnostic.PluginException: Cannot create extension 

### ISSUE THREAD

**Issue by pfrollo** [patricklx/intellij-emberjs-experimental#29]
### Description

Error occurred after enabling the plugin. 

I also had https://plugins.jetbrains.com/plugin/8049-ember-js/versions installed so I wonder if having both caused the issue. Once I removed 8049-ember-js I was not able to reproduce the issue. 

### Steps to Reproduce

- Enable plugin 

**Expected behavior:** [What you expect to happen]

- No error

**Actual behavior:** [What actually happens]

- Error occurred: com.intellij.diagnostic.PluginException: Cannot create extension 

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

IntelliJ IDEA 2023.1.2 (Ultimate Edition)
Build #IU-231.9011.34, built on May 16, 2023

Ember plugin: 2023.1.33

### Additional Information

com.intellij.diagnostic.PluginException: Cannot create extension (class=com.emberjs.index.EmberNameIndex) [Plugin: com.emberjs.experimental]
	at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:1096)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:70)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.createInstance(XmlExtensionAdapter.kt:31)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.java:445)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.access$200(ExtensionPointImpl.java:32)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl$1.next(ExtensionPointImpl.java:353)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.initAssociatedDataForExtensions(FileBasedIndexDataInitialization.java:77)
	at com.intellij.util.indexing.FileBasedIndexDataInitialization.prepareTasks(FileBasedIndexDataInitialization.java:132)
	at com.intellij.util.indexing.IndexDataInitializer.call(IndexDataInitializer.kt:19)
	at com.intellij.util.indexing.IndexDataInitializer$Companion$submitGenesisTask$1.invokeSuspend(IndexDataInitializer.kt:46)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
Caused by: com.intellij.diagnostic.PluginException: Cannot create class com.emberjs.index.EmberNameIndex (classloader=PluginClassLoader(plugin=PluginDescriptor(name=Ember Experimental.js, id=com.emberjs.experimental, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2023.1/plugins/EmberExperimental.js, version=2023.1.33, package=null, isBundled=false), packagePrefix=null, instanceId=448, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:1034)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.instantiateClass(XmlExtensionAdapter.kt:79)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter$SimpleConstructorInjectionAdapter.instantiateClass(XmlExtensionAdapter.kt:90)
	at com.intellij.openapi.extensions.impl.XmlExtensionAdapter.doCreateInstance(XmlExtensionAdapter.kt:50)
	... 16 more
Caused by: java.lang.AssertionError: ID with name 'ember.names' requested for plugin com.emberjs.experimental but registered for com.emberjs plugin. Please use an instance field to access corresponding ID.
	at com.intellij.util.indexing.ID.findByName(ID.java:137)
	at com.intellij.util.indexing.ID.create(ID.java:111)
	at com.emberjs.index.EmberNameIndex.<clinit>(EmberNameIndex.kt:37)
	at java.base/java.lang.invoke.DirectMethodHandle.allocateInstance(DirectMethodHandle.java:520)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:993)
	... 19 more
Caused by: java.lang.Throwable
	at com.intellij.util.indexing.ID.<init>(ID.java:93)
	at com.intellij.util.indexing.ID.create(ID.java:112)
	at com.emberjs.index.EmberNameIndex.<clinit>(EmberNameIndex.kt:31)
	at java.base/jdk.internal.misc.Unsafe.allocateInstance(Native Method)
	... 21 more

**Comment by patricklx** [comment]
You need to disable or remove the other ember plugin.
Error could be improved tough

**Comment by patricklx** [comment]
fixed by https://github.com/patricklx/intellij-emberjs-experimental/commit/bb53d7379ccb347cded117096e28ea0ddf47448d
