### ISSUE TITLE
Can't create a new Ember project from WebStorm "New Project" window.

### ISSUE THREAD

**Issue by jahrock** [patricklx/intellij-emberjs-experimental#77]
### Description

Can't create a new Ember project from WebStorm "New Project" window.

```
java.lang.Throwable: AWT events are not allowed inside write action: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=javax.swing.RepaintManager$ProcessingRunnable@6d8b8fa7,notifier=null,catchExceptions=false,when=1695800078768] on sun.awt.X11.XToolkit@1e681b57
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$postInit$0(ApplicationImpl.java:182)
	at com.intellij.ide.IdeEventQueue.runCustomProcessors(IdeEventQueue.kt:424)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:384)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:400)
        ...
```

### Steps to Reproduce

Initial steps to open "New Project" window: `File` -> `New` -> `Project`
Select project type: `Ember`
Select project options:
- Node interpreter: `~/.nvm/versions/node/v18.15.0/bin/node`
- Ember CLI: `npx ember-cli`
Click `Create` button

**Expected behavior:** A successfully created new Ember project or visual feedback that an error occoured.

**Actual behavior:** IDE internal Error occours & IDE isn't responsive until "Cancel" button has been triggered.

**Reproduces how often:** 100%

### Versions

- The first two lines of the `Help` -> `About` output:
WebStorm 2023.2.2
Build #WS-232.9921.42, built on September 12, 2023

- The version of `intellij-emberjs` (`Settings` -> `Plugins` -> `Ember.js`):
WebStorm 2023.2.5

- The version of `OS`
Ubuntu 23.04

### Additional Information
I could reproduce the issue as well with node 16 and locally installed ember-cli.
Project options:
- Node interpreter: `~/.nvm/versions/node/v16.15.1/bin/node`
- Ember CLI: `~/.nvm/versions/node/v16.15.1/lib/node_modules/ember-cli`

**Comment by patricklx** [comment]
Hi, 
Can you post more of the stack trace? Preferably until it reaches something related to ember plugin

**Comment by jahrock** [comment]
```
java.lang.Throwable: AWT events are not allowed inside write action: java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=javax.swing.RepaintManager$ProcessingRunnable@6d8b8fa7,notifier=null,catchExceptions=false,when=1695801374492] on sun.awt.X11.XToolkit@1e681b57
        at com.intellij.openapi.diagnostic.Logger.error(Logger.java:370)
        at com.intellij.openapi.application.impl.ApplicationImpl.lambda$postInit$0(ApplicationImpl.java:182)
        at com.intellij.ide.IdeEventQueue.runCustomProcessors(IdeEventQueue.kt:424)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:384)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:400)
        at com.intellij.openapi.progress.impl.PlatformTaskSupportKt.pumpEventsForHierarchy(PlatformTaskSupport.kt:379)
        at com.intellij.openapi.progress.impl.PlatformTaskSupportKt.access$pumpEventsForHierarchy(PlatformTaskSupport.kt:1)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$2.invoke(PlatformTaskSupport.kt:157)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$2.invoke(PlatformTaskSupport.kt:135)
        at com.intellij.openapi.application.impl.ModalityKt.inModalContext(modality.kt:12)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport.runWithModalProgressBlockingInternal(PlatformTaskSupport.kt:135)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport.access$runWithModalProgressBlockingInternal(PlatformTaskSupport.kt:41)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$1.invoke(PlatformTaskSupport.kt:123)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport$runWithModalProgressBlockingInternal$1.invoke(PlatformTaskSupport.kt:119)
        at com.intellij.openapi.progress.ContextKt.prepareThreadContext(context.kt:94)
        at com.intellij.openapi.progress.impl.PlatformTaskSupport.runWithModalProgressBlockingInternal(PlatformTaskSupport.kt:119)
        at com.intellij.openapi.progress.TasksKt.runWithModalProgressBlocking(tasks.kt:167)
        at com.intellij.ide.impl.ProjectUtilKt.runUnderModalProgressIfIsEdt(ProjectUtil.kt:710)
        at com.intellij.openapi.project.impl.ProjectImpl.save(ProjectImpl.kt:364)
        at com.emberjs.cli.EmberCliProjectConfigurator$Companion.setupEmber$lambda$0(EmberCliProjectConfigurator.kt:49)
        at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:992)
        at com.emberjs.cli.EmberCliProjectConfigurator$Companion.setupEmber(EmberCliProjectConfigurator.kt:46)
        at com.emberjs.cli.EmberCliProjectGenerator.generateProject(EmberCliProjectGenerator.kt:112)
        at com.emberjs.cli.EmberCliProjectGenerator.generateProject(EmberCliProjectGenerator.kt:21)
        at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.doGenerateProject(AbstractNewProjectStep.java:254)
        at com.intellij.ide.util.projectWizard.AbstractNewProjectStep.doGenerateProject(AbstractNewProjectStep.java:189)
        at com.intellij.ide.util.projectWizard.AbstractNewProjectStep$AbstractCallback.consume(AbstractNewProjectStep.java:180)
        at com.intellij.ide.util.projectWizard.ProjectSettingsStepBase$1.actionPerformed(ProjectSettingsStepBase.java:148)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
        at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
        at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
        at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
        at java.desktop/java.awt.Component.processEvent(Component.java:6422)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
        at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:121)
        at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:236)
        at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:234)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
        at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:234)
        at java.desktop/java.awt.Dialog.lambda$show$2(Dialog.java:1081)
        at java.desktop/sun.awt.SunToolkit.performOnMainThreadIfNeeded(SunToolkit.java:2164)
        at java.desktop/java.awt.Dialog.show(Dialog.java:1041)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:737)
        at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:462)
        at com.intellij.openapi.ui.DialogWrapper.doShow(DialogWrapper.java:1685)
        at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1643)
        at com.jetbrains.webstorm.WebStormNewProjectAction.actionPerformed(WebStormNewProjectAction.java:20)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.doPerformActionOrShowPopup(ActionUtil.java:339)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAwareWithCallbacks$4(ActionUtil.java:313)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareWithCallbacks(ActionUtil.java:362)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAwareWithCallbacks(ActionUtil.java:313)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$performAction$5(ActionMenuItem.java:300)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:226)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.performAction(ActionMenuItem.java:293)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$new$0(ActionMenuItem.java:68)
        at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$4(ActionMenuItem.java:115)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
        at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:94)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:115)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:526)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:558)
        at java.desktop/java.awt.Component.processMouseEvent(Component.java:6657)
        at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3385)
        at java.desktop/java.awt.Component.processEvent(Component.java:6422)
        at java.desktop/java.awt.Container.processEvent(Container.java:2266)
        at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
        at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4954)
        at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4581)
        at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4522)
        at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
        at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2808)
        at java.desktop/java.awt.Component.dispatchEvent(Component.java:4855)
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:794)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
        at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:766)
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:764)
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:763)
        at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:685)
        at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:633)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:588)
        at com.intellij.ide.IdeEventQueue.access$_dispatchEvent(IdeEventQueue.kt:67)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:369)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1$1.compute(IdeEventQueue.kt:368)
        at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:787)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:368)
        at com.intellij.ide.IdeEventQueue$dispatchEvent$processEventRunnable$1$1.invoke(IdeEventQueue.kt:363)
        at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$1(IdeEventQueue.kt:992)
        at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
        at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:992)
        at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$7(IdeEventQueue.kt:363)
        at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:861)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:405)
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by jahrock** [comment]
Thank you
